/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package excepciones;

import javax.swing.JOptionPane;

/**
 *
 * @author Jeffrey
 */
public class LanzadorExcepciones extends javax.swing.JFrame {

    /**
     * Creates new form LanzadorExcepciones
     */
    public LanzadorExcepciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAE = new javax.swing.JButton();
        jButtonNFE = new javax.swing.JButton();
        jButtonNPE = new javax.swing.JButton();
        jButtonAIOOBE = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lanzador de Excepciones");

        jButtonAE.setText("ArithmeticException");
        jButtonAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAEActionPerformed(evt);
            }
        });

        jButtonNFE.setText("NumberFormatException");
        jButtonNFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNFEActionPerformed(evt);
            }
        });

        jButtonNPE.setText("NullPointerException");
        jButtonNPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNPEActionPerformed(evt);
            }
        });

        jButtonAIOOBE.setText("ArrayIndexOutOfBoundsException ");
        jButtonAIOOBE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAIOOBEActionPerformed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTitle.setText("LANZADOR DE EXCEPCIONES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonNFE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNPE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAIOOBE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitle))
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButtonNFE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonNPE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAIOOBE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAEActionPerformed
        
        try{
            
            int dividirPorCero = 15/0;
        }
        catch(ArithmeticException e){
            JOptionPane.showMessageDialog(this, e, "Excepción atrapada", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonAEActionPerformed

    private void jButtonNFEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNFEActionPerformed
        
        try{
            String edadEntry = "29A";
        
            //intento de hacer un parse
            int edad = Integer.parseInt(edadEntry);
        }
        
        catch(NumberFormatException e ){
            JOptionPane.showMessageDialog(this, e, "Excepción atrapada", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonNFEActionPerformed

    private void jButtonNPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNPEActionPerformed
        
        try{
            String nombre = null;
            
            nombre.equals("Jeff");
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, e, "Excepción atrapada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonNPEActionPerformed

    private void jButtonAIOOBEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAIOOBEActionPerformed
        
        try{
            String[] frutas = new String[]{"Manzana", "Pera", "Naranja"};
            
            //intento de apuntar a un subíndice que NO existe
            String terceraFruta = frutas[3]; //recordar que los arreglos comienzan en 0
        }
        catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this, e, "Excepción atrapada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAIOOBEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LanzadorExcepciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LanzadorExcepciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LanzadorExcepciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LanzadorExcepciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LanzadorExcepciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAE;
    private javax.swing.JButton jButtonAIOOBE;
    private javax.swing.JButton jButtonNFE;
    private javax.swing.JButton jButtonNPE;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
